
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================


module DE10_LITE_Golden_Top (

    input  [9:0] SW,
    output [9:0] LEDR

);

    C4M1P3 u1 (
        .SW(SW[8:0]),
        .LEDR(LEDR[4:0])
    );

endmodule