
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================
module DE10_LITE_Golden_Top (
    input  [9:0] SW,
    output [6:0] HEX0,
    output [6:0] HEX1,
    output [6:0] HEX3,
    output [6:0] HEX5
);

    C4M1P4 u1 (
        .SW(SW),
        .HEX0(HEX0),
        .HEX1(HEX1),
        .HEX3(HEX3),
        .HEX5(HEX5)
    );

endmodule